### ISSUE TITLE
[建议]常驻进程运行建议增加监控逻辑

### ISSUE THREAD

**Issue by zhiqiangwong** [peng49/gocron#3]
稍微试用了一下，发现在进程管理处增加一个常驻进程后，当该进程自行结束运行时似乎并未有相关的监控去监听 pid 运行状态？导致实际上进程已经结束运行但进程管理处任然显示为运行中的状态。建议增加监听进程功能并能自动重新拉起进程。该功能在实际使用中或为刚需功能。

**Comment by peng49** [comment]
pid的运行状态时有进行30秒一次的监听的，如果进程停止，会自动重启
